services:
  workmate_private_redis:
    image: redis:7-alpine
    container_name: workmate_private_redis
    restart: unless-stopped
    networks:
      - core_network

  workmate_private_backend:
    build: ./backend
    container_name: workmate_private_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - workmate_private_redis
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - core_network

  workmate_private_celery:
    build: ./backend
    container_name: workmate_private_celery
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - workmate_private_redis
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - core_network

  workmate_private_celery_beat:
    build: ./backend
    container_name: workmate_private_celery_beat
    command: celery -A app.celery beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - workmate_private_redis
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - core_network

  workmate_private_ui:
    build:
      context: ./frontend
      args:
        API_URL: ${API_URL:-https://api.workmate-private.intern.phudevelopement.xyz/api/v1}
    container_name: workmate_private_ui
    restart: unless-stopped
    networks:
      - core_network

networks:
  core_network:
    external: true
